name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@477b21f02be01bcb8030d50f37cfec92bfa615b6
      with:
        ruby-version: 3.0.0
      
    - name: Install dependencies
      run: bundle install
      
    - name: Setup Cocoapods
      uses: maxim-lobanov/setup-cocoapods@v1
      with: 
        podfile-path: Example/Podfile.lock 
     
    - name: Run Fastlane 
    - run: bundle exec fastlane test
      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
